title: Reinhart Previano K.
description: Blog repository

destination: docs/

future: true

plugins:
  - jekyll-archives
#  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

jekyll-archives:
  enabled: all
  layouts: 
    year: archive-year
    month: archive-month
    day: archive-day
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/posts/:year/'
    month: '/posts/:year/:month/'
    day: '/posts/:year/:month/:day/'
    tag: '/posts/tag/:name/'
    category: '/posts/category/:name/'

highlighter: rouge

permalink: /posts/:year/:month/:day/:title:output_ext

paginate: 12
paginate_path: "/posts/page:num/"